### ISSUE TITLE
Error when replacing song files. 

### ISSUE THREAD

**Issue by EKTb0i** [ZSabakh/IVRadioEditor#1]
Everytime I try to replace a song. I keep getting this error "An error occurred: [WinError 2] The system cannot find the file specified". Idk what I'm doing wrong.

**Comment by ZSabakh** [comment]
I was able to replicate the issue only when FFmpeg was missing from the system. I added checks on app startup to ensure that FFmpeg exists. If it doesn't, there is now an option to download and automatically install it from 
https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip

Update is released in 0.1.3 #2 
https://github.com/ZSabakh/IVRadioEditor/releases/tag/0.1.3
